# C compiler
CC = /home/praveen/FYP/Repo/Rigel-FYP/Identifier/summaryIdentifier/omppNew/ompp/bin/kinst-ompp clang -L/home/praveen/FYP/Repo/Rigel-FYP/Identifier/summaryIdentifier/omppNew/ompp/lib -lompp -fopenmp


2mm:
	$(CC) tsc.c dummy.c -o testapp -lm

clean:
	rm -f *.o
